// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testnativeorientationwidget.proxies;

public enum ENUM_Orientation
{
	portrait("ca297467-552d-47f8-b2ff-29b2d72fe076"),
	landscape("10e5e0ff-ff5a-4650-afd4-6b619f2ff94c");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Orientation(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
