// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("d957f02f-375d-4cbe-b21b-09e20fd432de"),
	Geocodio("a4c04752-93bb-4067-bb66-761a7268b26a"),
	LocationIQ("3c0ed886-073a-4da5-96b3-7f21ad579d16"),
	MapQuest("adc84ba7-ccb2-4cf5-b1b2-167a8ac8042f");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
