// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("d509cffe-9367-416c-8bec-93c082812262"),
	startsWith("8a33e9da-78ad-4d90-9bf6-50d9c1cb878e"),
	endsWith("fcff849f-4df0-43ca-b32e-b517f9e5bdad"),
	between("b35ad2e0-8d56-4943-b4b8-a13137bb574d"),
	greater("5f1768c8-885f-4c57-989a-a520300619a2"),
	greaterEqual("ade35990-ec28-4aa6-8909-fa1fc837701f"),
	equal("b6fe4cd9-be72-43d7-ad29-51310596f4f1"),
	notEqual("30cabdc2-c228-4617-82b5-ae7c98f533bf"),
	smaller("e933b285-cb2e-4d54-9bbf-c9edad4cd1c6"),
	smallerEqual("d6209ec8-07a9-4f06-888f-f834db2c3336"),
	empty("f6cd2ea1-1e75-4ec4-be65-edeb806e1150"),
	notEmpty("f7277560-fe2a-4d93-b8c3-5e9180ffa238");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
