// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testnativeorientationwidget.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the TestNativeOrientationWidget module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestData_CreateRowsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestNativeOrientationWidget.ACT_TestData_CreateRows");
		return builder;
	}

	public static void aCT_TestData_CreateRows(IContext context)
	{
		aCT_TestData_CreateRowsBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestData_DeleteAllBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestNativeOrientationWidget.ACT_TestData_DeleteAll");
		return builder;
	}

	public static void aCT_TestData_DeleteAll(IContext context)
	{
		aCT_TestData_DeleteAllBuilder().execute(context);
	}
}
