// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("f3070230-539e-4b00-bd3f-b1ab03b9335d"),
	denied("68f22e20-e3d8-4da9-95bb-5010dd10c84e"),
	limited("a04c3fa6-1bee-43f4-84b4-ce74c9c80fdc"),
	granted("402cb81e-6202-48e5-a52a-bd0e0188f980"),
	blocked("d22847fd-807b-4338-913b-2e3cbb4c7579");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
