// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("d98b75d2-8b7c-4636-af5d-5f962f8cde19"),
	denied("aa7b1474-8268-46a6-aee0-ed3fcc6d9797"),
	limited("f1631b9f-996a-41e9-a06f-2dbfbac595fe"),
	granted("d790bb6b-932a-4091-9def-707319a70dd5"),
	blocked("d44aa565-e243-425e-ac61-3ab4634ec28b");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
