// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("a22376c3-67ef-4627-ad2c-cbe1d4a230ce"),
	denied("f5fb688f-af14-4b4a-b2b6-d08f2a9cb318"),
	limited("3d20fcb5-8ab5-4515-9e8c-e0bdcee4cda5"),
	granted("223a33cd-15ed-495f-9938-9cbc80af22cd"),
	blocked("c1262fe9-a110-4ca0-ae88-11341c5cbba0");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
