// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("8addd6c9-04c0-4847-84c6-86275bbc59a8"),
	low("1612678a-284b-4bb9-a31d-52d5b2824e71"),
	medium("eab5e59e-9942-48ba-8f01-304a4cfd4c37"),
	high("7237776d-dadd-4372-8c3d-19b7d472504c"),
	custom("17b02790-fc0c-4df0-935d-e81b2b18e5c2");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
