// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("bc438755-1088-4fb2-bf50-76b0083fdee3"),
	low("4a975138-478f-42cf-af55-51a2d1c2b697"),
	medium("fd690d2e-5609-4fb8-ba1c-3b03f4ecaa3c"),
	high("40151943-1a1c-4195-afeb-941a8e04e960"),
	custom("44e666e5-2683-48a0-9393-7686b5c7e6f7");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
