// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("7f6c25e4-a317-4b46-b2fd-f4c300192ed3"),
	low("86eaf7c5-fa53-49aa-93a8-1b9678504e1e"),
	medium("a706e654-daee-4e06-807c-e84cdba6f0b7"),
	high("4f054ab7-698d-4c12-8d31-3c7c4453b2e3"),
	custom("670f0581-2197-4112-a15e-27ff7bdd44f1");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
